SELECT O.PRODUCT_ID, P.PRODUCT_NAME, (P.PRICE * SUM(O.AMOUNT)) AS TOTAL_SALES
FROM FOOD_ORDER O
JOIN FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE YEAR(O.PRODUCE_DATE) = 2022 AND MONTH(O.PRODUCE_DATE) = 5
GROUP BY O.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID;
