SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
(SELECT MAX(E1.SIZE_OF_COLONY) 
FROM ECOLI_DATA E1
WHERE YEAR(E1.DIFFERENTIATION_DATE) = YEAR(E.DIFFERENTIATION_DATE))
- E.SIZE_OF_COLONY AS YEAR_DEV, 
E.ID
FROM ECOLI_DATA E
ORDER BY YEAR(DIFFERENTIATION_DATE), YEAR_DEV;