# 1. 각각 몇 세대인지 구하기 
WITH RECURSIVE FAMILY AS (

    SELECT ID, PARENT_ID, 1 AS GENERATION 
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL
    
    UNION ALL 
    
    SELECT E.ID, E.PARENT_ID, F.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN FAMILY F ON E.PARENT_ID = F.ID 
)

# 2. 자식 없는 애들만 남겨두고 세기 
SELECT COUNT(1) AS COUNT, F.GENERATION 
FROM FAMILY F
LEFT JOIN ECOLI_DATA E ON F.ID = E.PARENT_ID
WHERE E.ID IS NULL
GROUP BY GENERATION
ORDER BY GENERATION;