-- 조인
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO I
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
WHERE N.FISH_NAME IN ('BASS', 'SNAPPER')

-- 서브쿼리
SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO I
WHERE I.FISH_TYPE IN ( 
(SELECT N.FISH_TYPE
FROM FISH_NAME_INFO N 
WHERE N.FISH_NAME IN ('BASS', 'SNAPPER')));