SELECT ROUTE, 
    CONCAT(ROUND(SUM(D_BETWEEN_DIST), 2), 'km') AS TOTAL_DISTANCE, 
    CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC;

-- 'km'를 붙여놔서 문자열로 비교되기 떄문에 TOTAL_DISTANCE 그대로 쓰면 ORDER BY가 꼬일 수 있음 