SELECT EMP_NO, EMP_NAME, GRADE, 
    CASE 
        WHEN GRADE = 'S' THEN SAL * 0.20
        WHEN GRADE = 'A' THEN SAL * 0.15
        WHEN GRADE = 'B' THEN SAL * 0.10
        ELSE 0
    END AS BONUS
FROM (
    SELECT E.EMP_NO, E.EMP_NAME, E.SAL,
    CASE 
        WHEN AVG(G.SCORE) >= 96 THEN 'S'
        WHEN AVG(G.SCORE) >= 90 THEN 'A'
        WHEN AVG(G.SCORE) >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE
    FROM HR_EMPLOYEES E
    JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
    GROUP BY E.EMP_NO, E.EMP_NAME, E.SAL
) A
ORDER BY EMP_NO;